version: '3'
services:
  exemple-api:
    container_name: exemple-api
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=

volumes:
  redis-data:
